[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = 'neocomplete.vim'
depends = 'neocomplete.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
depends = 'neocomplete.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = 'neocomplete.vim'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = 'neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'
hook_post_source = '''
    call unite#custom#profile('default','context',{
       \ 'direction':'below',
       \ 'prompt_direction':'top'})
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = 'previm'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/Tweetvim'
rev = 'dev'
depends = ['webapi-vim', 'open-browser.vim', 'twibill.vim']
on_cmd = ['TweetVimUserStream', 'TweetVimSay', 'TweetVimCommandSay', 'TweetVimHomeTimeLine']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'zerowidth/vim-copy-as-rtf'
on_cmd = ['CopyRTF']
