[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('python3')'''
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
on_event = ['InsertEnter']
hook_source = '''
    call deoplete#initialize()
    call deoplete#custom#option({
        \ 'yarp': v:true,
        \ 'smart_case': v:true,
        \ 'skip_multibyte': v:true,})
    call deoplete#custom#option('keyword_patterns', {
        \ 'tex': '\\?[a-zA-Z_]+',
        \ 'markdown': '\\?[a-zA-Z_]+',})
    call deoplete#custom#source('_', 'converters', [
        \ 'converter_remove_overlap',
        \ 'converter_truncate_abbr',
        \ 'converter_truncate_menu',
        \ ])
    call deoplete#enable()
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''has('python3')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''has('python3')'''

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim','neocomplete.vim']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'
# on_source = ['deoplete.nvim', 'neocomplete.vim']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['tex', 'text', 'markdown']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/unite.vim'
on_source = ['denite.nvim']
hook_post_source = '''
    call unite#custom#profile('default','context',{
       \ 'direction':'below',
       \ 'prompt_direction':'top'})
    call unite#custom#source('file_mru', 'ignore_pattern', '\v^gina:')
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/Tweetvim'
depends = ['webapi-vim', 'open-browser.vim', 'twibill.vim']
on_cmd = ['TweetVimSay', 'TweetVimCommandSay', 'TweetVimHomeTimeline']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
if = '''executable('go')'''
on_ft = 'go'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = 'previm'

[[plugins]]
repo = 'Shougo/defx.nvim'
if = '''has('python3')'''
on_cmd = 'Defx'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = '''
call defx#custom#column('icon', {
    \ 'directory_icon': '▸',
    \ 'opened_icon': '▾',
    \ 'root_icon': ' ',
    \ })
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = '''has('python3')'''
on_cmd = 'Denite'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
