prompt_order = [
    "username",
    "hostname",
    "time",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "golang",
    "java",
    "nodejs",
    "python",
    "ruby",
    "rust",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "line_break",
    "jobs",
    "battery",
    "character",
]
add_newline = false

[character]
symbol = "ξ(✿ ❛‿❛)ξ"
error_symbol = "人◕ ‿‿ ◕人"
style_success = "yellow"
use_symbol_for_status = true

[directory]
truncation_length = 3
style = "purple"

[git_branch]
style = "green"

[hostname]
ssh_only = false
style = "blue"

[time]
disabled = false
style = "red"
