add_newline = false

[character]
symbol = "ξ（✿ ❛‿❛）ξ"
style_success = "yellow"

[directory]
truncation_length = 3
style = "blue"

[git_branch]
symbol = ""
style = "green"

[hostname]
ssh_only = false
style = "white"
